# 101 Pandas Exercise for Data Analysis


Source inspriration:
https://www.machinelearningplus.com/python/101-pandas-exercises-python/

In [1]:
import pandas as pd
import numpy as np

In [2]:
#How to check the version?
pd.__version__

'0.24.2'

In [3]:
# Creating an array from range

createarr = np.arange(10)
createarr2 = np.arange(10, 23, dtype = float)
createarr3 = np.arange(start = 30, stop = 48, dtype = float)
createarr4 = np.arange(start = 31, stop = 48, step = 4, dtype = float)

#creating an array using defined numbers
createarr6 = np.array([4,10,11,12])

# creating an array with defined range and defined number of elemets spaced equally among each other
createarr7 = np.linspace (2,12, 5)

print(createarr)
print(createarr2)
print(createarr3)
print(createarr4)
print('----')

print(createarr6)
print('----')
print(createarr7)



[0 1 2 3 4 5 6 7 8 9]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22.]
[30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47.]
[31. 35. 39. 43. 47.]
----
[ 4 10 11 12]
----
[ 2.   4.5  7.   9.5 12. ]


In [4]:
#How to create a series from a list, numpy array and dict?

#input
mylist = list('abcedf')
mylist2 = list(['ab','cd','ef'])

myarr = np.arange(5,11, dtype = int)
mydict = dict(zip(mylist, myarr))

print(mylist)
print(mylist2)
print(myarr)
print(mydict)

mylistasseries = pd.Series(mylist)
mylist2asseries = pd.Series(mylist2)
myarrasseries = pd.Series(myarr)
mydictasseries = pd.Series(mydict)

print(mylistasseries)
print(mylist2asseries)
print(myarrasseries)
print(mydictasseries)




['a', 'b', 'c', 'e', 'd', 'f']
['ab', 'cd', 'ef']
[ 5  6  7  8  9 10]
{'a': 5, 'b': 6, 'c': 7, 'e': 8, 'd': 9, 'f': 10}
0    a
1    b
2    c
3    e
4    d
5    f
dtype: object
0    ab
1    cd
2    ef
dtype: object
0     5
1     6
2     7
3     8
4     9
5    10
dtype: int32
a     5
b     6
c     7
e     8
d     9
f    10
dtype: int64


In [5]:
#How to convert a series into a column of a dataframe?
#input
mylist = list('daecfb')
mycountry = list(['Canada','France','Sweden', 'Japan', 'Netherland', 'Germany'])
myarr = np.array([5,7,3,6,7,5])

myset = {'Standing': mylist, 'Country':mycountry, 'Goals': myarr}

print(myset)

df = pd.DataFrame(myset)

print(df)



{'Standing': ['d', 'a', 'e', 'c', 'f', 'b'], 'Country': ['Canada', 'France', 'Sweden', 'Japan', 'Netherland', 'Germany'], 'Goals': array([5, 7, 3, 6, 7, 5])}
  Standing     Country  Goals
0        d      Canada      5
1        a      France      7
2        e      Sweden      3
3        c       Japan      6
4        f  Netherland      7
5        b     Germany      5


In [6]:
# check the type of the object

type(df)

pandas.core.frame.DataFrame

In [12]:
#add to existing dataframe. Continuation of previous step

print(df)

df['Roster Count'] = [15,16,16,17,15,18]

print(df)

  Standing     Country  Goals  Roster Count
0        d      Canada      5            15
1        a      France      7            16
2        e      Sweden      3            16
3        c       Japan      6            17
4        f  Netherland      7            15
5        b     Germany      5            18
  Standing     Country  Goals  Roster Count
0        d      Canada      5            15
1        a      France      7            16
2        e      Sweden      3            16
3        c       Japan      6            17
4        f  Netherland      7            15
5        b     Germany      5            18


In [13]:
#add to existing dataframe by first creating a copy of the orginal data frame. Continuation of previous step
print (df)

capital = ['Ottawa', 'Paris', 'Stockholm', 'Tokyo', 'Amsterdam', 'Berlin']

print(type(capital))

df2 = df.assign(Capital = capital)

print(df2)

  Standing     Country  Goals  Roster Count
0        d      Canada      5            15
1        a      France      7            16
2        e      Sweden      3            16
3        c       Japan      6            17
4        f  Netherland      7            15
5        b     Germany      5            18
<class 'list'>
  Standing     Country  Goals  Roster Count    Capital
0        d      Canada      5            15     Ottawa
1        a      France      7            16      Paris
2        e      Sweden      3            16  Stockholm
3        c       Japan      6            17      Tokyo
4        f  Netherland      7            15  Amsterdam
5        b     Germany      5            18     Berlin


In [14]:
#How to give a name to a series index? The name of the series will be the column name when created as a column in a Dataframe

#input
myseries = pd.Series(list([1,5,3,2,3,4]))

myseries.head()

myseries.name = 'Podium Appearance'
myseries.head()


df3 = pd.concat([df2,myseries], axis =1)

print (df3)

  Standing     Country  Goals  Roster Count    Capital  Podium Appearance
0        d      Canada      5            15     Ottawa                  1
1        a      France      7            16      Paris                  5
2        e      Sweden      3            16  Stockholm                  3
3        c       Japan      6            17      Tokyo                  2
4        f  Netherland      7            15  Amsterdam                  3
5        b     Germany      5            18     Berlin                  4


In [16]:
# Get a sample set from any data
# let n be the number of outputs desired. .sample(n)
df.sample(3)


Standing  Country  Goals  Roster Count
0        d   Canada      5            15
5        b  Germany      5            18
2        e   Sweden      3            16

## More Advanced Topics

In [20]:
#How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
np.random.seed(1) #set a seed for replicability

ser = pd.Series(np.random.normal(loc = 10, scale = 5, size = 25)) # mean of 10, standard deviation of 10, 25 results
print (ser)

np.percentile(ser, q=[0,25,50,75,100])




0     18.121727
1      6.941218
2      7.359141
3      4.635157
4     14.327038
5     -1.507693
6     18.724059
7      6.193965
8     11.595195
9      8.753148
10    17.310540
11    -0.300704
12     8.387914
13     8.079728
14    15.668847
15     4.500544
16     9.137859
17     5.610708
18    10.211069
19    12.914076
20     4.496904
21    15.723619
22    14.507954
23    12.512472
24    14.504280
dtype: float64


array([-1.50769348,  6.1939655 ,  9.13785896, 14.50427975, 18.72405882])

In [10]:
# Get the frequency counts of unique items of a series or a column in dataframe
df3.info()

# check the unique counts per column
print(df3['Standing'].value_counts())
print(df3['Podium Appearance'].value_counts())

# check the unique count for a series
print(myseries.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
Standing             6 non-null object
Country              6 non-null object
Goals                6 non-null int32
Roster Count         6 non-null int64
Capital              6 non-null object
Podium Appearance    6 non-null int64
dtypes: int32(1), int64(2), object(3)
memory usage: 344.0+ bytes
f    1
b    1
d    1
e    1
c    1
a    1
Name: Standing, dtype: int64
3    2
5    1
4    1
2    1
1    1
Name: Podium Appearance, dtype: int64
3    2
5    1
4    1
2    1
1    1
Name: Podium Appearance, dtype: int64


In [10]:
# Bin numeric series to n groups of equal size
array = np.random.random_sample((20))

print(array)

# notice the array is change to a series first before binning
array2 = pd.qcut(pd.Series(array), q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'])
# bins are assigned by index in the format of a category
print(array2)
type(array2)

# combine the lables and the array into a dataframe

myset = {'Random Value': pd.Series(array), 'Percentile': array2}

df = pd.DataFrame(myset)

print(df)




[0.26992789 0.89588622 0.42809119 0.96484005 0.6634415  0.62169572
 0.11474597 0.94948926 0.44991213 0.57838961 0.4081368  0.23702698
 0.90337952 0.57367949 0.00287033 0.61714491 0.3266449  0.5270581
 0.8859421  0.35726976]
0      2nd
1      9th
2      4th
3     10th
4      8th
5      7th
6      1st
7     10th
8      5th
9      6th
10     4th
11     2nd
12     9th
13     6th
14     1st
15     7th
16     3rd
17     5th
18     8th
19     3rd
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]
    Random Value Percentile
0       0.269928        2nd
1       0.895886        9th
2       0.428091        4th
3       0.964840       10th
4       0.663441        8th
5       0.621696        7th
6       0.114746        1st
7       0.949489       10th
8       0.449912        5th
9       0.578390        6th
10      0.408137        4th
11      0.237027        2nd
12      0.903380        9th
13      0.573679        6th
14      0.002870        1st
15      0.617145

In [8]:
# Find the Mean Square Error (MSE) of the truth and the predicted values (both in Series format)
# MSE is the average (mean) of earch pairs (truth - prediction)^2

np.random.seed(99) #set a seed for replicability

truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

print(truth)
print (pred)

np.mean((truth - pred)**2)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    0.672279
1    1.488078
2    2.825495
3    3.031446
4    4.808050
5    5.565617
6    6.297622
7    7.046696
8    8.990627
9    9.006826
dtype: float64


0.34176268277743493

In [10]:
# Measure the time it takes to execute code

import time
start = time.time()

np.random.seed(99) #set a seed for replicability

truth = pd.Series(range(8))
pred = pd.Series(range(8)) + np.random.random(8)

print(truth)
print (pred)

np.mean((truth - pred)**2)

end = time.time()

print("--- %s seconds ---" % (end - start))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
dtype: int64
4    4
7    7
6    6
dtype: int64
0    0.672279
1    1.488078
2    2.825495
3    3.031446
4    4.808050
5    5.565617
6    6.297622
7    7.046696
dtype: float64
--- 0.03590583801269531 seconds ---


In [21]:
#count the number of characters in each string in a series
ser = pd.Series(['how', 'best to', 'kick', 'ass?'])

ser.str.len()

0    3
1    7
2    4
3    4
dtype: int64

In [5]:
#count the number of characters in each string in a column in a dataframe
#input- create sample dataframe
code= list(['AA','VS', 'DL','NK'])
name = list(['American Airlines Inc.','Virgin America','Delta Airlines', 'Spirit Air Lines'])
avgdelayhour = np.array([5,1,4,6])

flightset = {'Carrier Code': code, 'Name':name, 'Avg Delay Hour': avgdelayhour}

dfflight = pd.DataFrame(flightset)

print(dfflight)

dfflight['Name Length']= dfflight.Name.map(lambda x: len(x))

print(dfflight)

#exclude certain characters in the count, spaces (or anything really). define exclusion in .count(i)

dfflight['Name Length without space']= dfflight.Name.map(lambda x: len(x) - x.count(' '))

print(dfflight)


  Carrier Code                    Name  Avg Delay Hour
0           AA  American Airlines Inc.               5
1           VS          Virgin America               1
2           DL          Delta Airlines               4
3           NK        Spirit Air Lines               6
  Carrier Code                    Name  Avg Delay Hour  Name Length
0           AA  American Airlines Inc.               5           22
1           VS          Virgin America               1           14
2           DL          Delta Airlines               4           14
3           NK        Spirit Air Lines               6           16
  Carrier Code                    Name  Avg Delay Hour  Name Length  \
0           AA  American Airlines Inc.               5           22   
1           VS          Virgin America               1           14   
2           DL          Delta Airlines               4           14   
3           NK        Spirit Air Lines               6           16   

   Name Length without space 

In [11]:
# How to get the mean, min, max using Group By
np.random.seed(3)
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weight = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())

weight.groupby(fruit).mean()

# let's try to put the 2 lists into a Dataframe and see if it works
fruitsets


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'apple', 'banana', 'apple', 'apple', 'apple', 'banana', 'banana', 'carrot', 'banana']


apple     4.25
banana    7.00
carrot    5.00
dtype: float64